/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ipssi.rfid.ui.controller;

import java.util.logging.Logger;

import javax.swing.JOptionPane;

/**
 *
 * @author Vi$ky
 */
public class ConfirmationDialog extends javax.swing.JDialog {

	/**
	 * Creates new form ConfirmationDialog
	 */
	private static final Logger log = Logger.getLogger(ConfirmationDialog.class.getName());
	public ConfirmationDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	public static int getDialogBox(final java.awt.Frame parent, boolean modal, Object[] options, String Msg) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				ConfirmationDialog dialog = new ConfirmationDialog(parent, true);
			}
		});
		// Object[] options = {" Re-Enter ", " Continue "};
		int response = JOptionPane.showOptionDialog(parent, Msg, "Confirm", JOptionPane.YES_NO_OPTION,
				JOptionPane.INFORMATION_MESSAGE, null, // do not use a custom Icon
				options, // the titles of buttons
				options[0]); // default button title

		if (response == JOptionPane.NO_OPTION)/* click Next */ {
			System.out.println("No button clicked " + response);
		} else if (response == JOptionPane.YES_OPTION)/* click Recapture */ {
			System.out.println("Yes button clicked " + response);
		} else if (response == JOptionPane.CLOSED_OPTION) {
			System.out.println("JOptionPane closed " + response);
		}
		// else if(response == JOptionPane.CLOSED_OPTION) {
		// System.out.println("JOptionPane closed " + response);
		// }
		return response;

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				formKeyPressed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 400, Short.MAX_VALUE));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 91, Short.MAX_VALUE));

		pack();
		// setVisible(true);
	}// </editor-fold>//GEN-END:initComponents

	private void formKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_formKeyPressed

	}// GEN-LAST:event_formKeyPressed

	/**
	 * @param args
	 *            the command line arguments
	 */

	// Variables declaration - do not modify//GEN-BEGIN:variables
	// End of variables declaration//GEN-END:variables
}
